# Generated by Django 5.0.6 on 2024-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='images/')),
                ('aadhaar_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
            ],
        ),
    ]
