# Generated by Django 5.0.6 on 2024-07-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SharedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('name_shared', models.BooleanField(default=False)),
                ('phone_shared', models.BooleanField(default=False)),
                ('age_shared', models.BooleanField(default=False)),
                ('sex_shared', models.BooleanField(default=False)),
                ('caste_shared', models.BooleanField(default=False)),
                ('address_shared', models.BooleanField(default=False)),
                ('marital_status_shared', models.BooleanField(default=False)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ID.details')),
            ],
        ),
    ]
