# Generated by Django 5.0.6 on 2024-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID', '0002_remove_details_qrcode_details_phone_shareddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddetails',
            name='details',
        ),
        migrations.AddField(
            model_name='shareddetails',
            name='shared_id',
            field=models.IntegerField(default=0),
        ),
    ]
