# Generated by Django 5.0.6 on 2024-07-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID', '0003_remove_shareddetails_details_shareddetails_shared_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='shareddetails',
            name='shared_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
